### ISSUE TITLE
Don't remove filenames

### ISSUE THREAD

**Issue by christianseel** [modxcms/Gallery#22]
Currently all filnames are replaced by the image id. This is not good for SEO. I'd like to have filesnames like `{{name}}.{{id}}.{{extension}}`.

I found some lines of code that seemed to build the id based filenames in `/core/components/gallery/processors/mgr/item/` like ajaxupload.php or batchupload.php. But changing ajaxupload.php at line 46 didn't change anything:

```
$itenname = $modX->filterPathSegment($item->get('name'));
$extension = end(explode('.', $filenm));
$filename = $itenname.'.'.$item->get('id').'.'.$extension;
```

Can anybody point me to the correct file where I'd need to edit it?

**Comment by kindla** [comment]
christianseel,

You solved this problem? If the answer is yes then how?

Thanks!

**Comment by christianseel** [comment]
Nope, but I'd recommend using MoreGallery by modmore. Way better features!
