### ISSUE TITLE
Could not create directory (possibly already exists?)

### ISSUE THREAD

**Issue by lithiumlab** [modxcms/Gallery#34]
I'm getting this warning in the console  every time a file gets uploaded.

` ` `
[Gallery] Could not create directory (possibly already exists?): assets/gallery/5/
` ` ` 

The files are being uploaded correctly, folder created and thumbs generated.
But this error keeps coming.

I'm using windows server 2008 r2
How do i make sure what is the user being used by the php process?

**Comment by robcarey** [comment]
I am also getting this error every time galleries are created.   Functionality seems to be fine - galleries are in fact created and I can upload images.... just getting the logs reporting the errors.
