### ISSUE TITLE
Change location of cache folder

### ISSUE THREAD

**Issue by ricardo-lewis** [modxcms/Gallery#49]
Is it possible to change the location of the image cache from **assets/components/gallery/cache**?

I have a separate cache folder specified for MODX and I would like Gallery to use that as well.

**Comment by tassu** [comment]
Agree this! And it seems that clearing cache (level 2) is not affecting in this folder. (Using pthumb and csssweet extras.)

And when using extra like pthumb it would be nice to integrate that working with Gallery. Pthumb has much more nicer naming policy etc.
