### ISSUE TITLE
Multi-Upload doesn't work - ignores Media Source BasePath

### ISSUE THREAD

**Issue by twincreekmedia** [modxcms/Gallery#53]
**Gallery Version: 1.7 on MODX 2.3.1**

Regular Upload works (with Media Source BaseBath set), Multi-Upload doesn't report error but shows broken image & phpthumb errors in error log (file does not exist). Looks like the Multi-Upload ignores the Media Source BasePath.

**Fix**
_/core/components/gallery/model/gallery/galalbum.class.php_
On line 224:
replace _$target = fopen($this->getPath(true).$shortName, "w");_
with _$target = fopen($mediaSource->getBasePath().$this->getPath(true).$shortName, "w");_

**Comment by tazeverywhere** [comment]
Gallery Version: 1.7.1 on MODX 2.6.5

Thanks ! works .
