### ISSUE TITLE
System Setting - Number of images shown

### ISSUE THREAD

**Issue by phillipdade** [modxcms/Gallery#61]
Hi

At present, when viewing a album, a default of 20 images are displayed. Could there be a system setting configured for the Gallery plugin that allows us to change the default number of images that are displayed in the album?

Regards

Phillip

**Comment by florian-rabis** [comment]
Do mean the list in the manager? Is there no input field below, where you can type in how many images should be shown?

**Comment by phillipdade** [comment]
Yes, I managed to change the default with the 'default_per_page' setting on each site. This pulls the change across to the Gallery album. I just forgot to close this issue/ticket.
