### ISSUE TITLE
[Bug] Backend Pagination Page Size Not Working

### ISSUE THREAD

**Issue by exside** [modxcms/Gallery#68]
If another (than 20) page size for paginated ExtJS components is defined via Global MODX System Settings, let's say 100, then we get strange behaviour in the Gallery CMP which looks like this:
![screen shot 2016-02-29 at 14 46 12](https://cloud.githubusercontent.com/assets/445501/13396263/ef5cc890-def3-11e5-90d2-848c9e73eecf.png)

basically the CMP is not respecting the custom page size and just shows 20 items...one then has to manually refresh the grid to see all items, clients get regularly confused by this...

**Comment by SilverMabol** [comment]
2.0.3 have the same problem
