### ISSUE TITLE
Gallery loses all images in albums

### ISSUE THREAD

**Issue by soydemadrid** [modxcms/Gallery#72]
Hi I hope you can please help. I've just upgraded a server to Ubuntu 16.04 which uses MySQL 5.7.

Modx and everything works perfectly, but the Gallery has lost all it's images. When I click on an album it just says "No files match the specified filter."

Looking in the Modx Error Reporting sections reveals a problem:

```
(ERROR @ /home/public_html/core/xpdo/om/xpdoobject.class.php : 240) Error 42000 executing statement: 
Array
(
    [0] => 42000
    [1] => 1055
    [2] => Expression #13 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'siteusername.AlbumItems.rank' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
)
```

Any help to fix this would be really appreciated, even if we can just patch it temporary etc for now?

Thanks very much again for any help :)

**Comment by Jako** [comment]
This is a MySQL 5.7 issue and could be fixed by adding the column `siteusername.AlbumItems.rank` to the SELECT list.

**Comment by Jako** [comment]
Do you have any other Gallery related packages installed? I can't find any groupBy or GROUP BY clause in the Gallery repository. Something that creates the `siteusername.` prefix.

**Comment by soydemadrid** [comment]
Hi thanks for the help! It is really appreciated.

No I only have Gallery installed but can confirm this happens on a few different modx sites I've set up. The siteusername.AlbumItems.rank is different for each site depending on the actual apache vhost username. I just renamed it here to something generic.

How so I add the column to the SELECT list to fix this properly?

Thanks once again!

**Comment by soydemadrid** [comment]
Hi also can I just add that Sevet in mysql irc has advised to add to this ticket that this bug is a bug in sql not mysql because what has been done is nondeterministic

**Comment by soydemadrid** [comment]
Ok after help on IRC from the mysql pro "Sevet" - he has come up with a temporary fix by setting the mysql mode without "only_full_group_by" in /core/xpdo/om/mysql/connect.inc.php

Just add this code:
`$this->pdo->exec("SET SESSION sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';");`

after line 12: $this->pdo->exec($sql); 

so the file then looks like this:

```
<?php
if (!empty($this->config['charset'])) {
    $sql = '';
    $method = 'SET NAMES';
    if (!empty($this->config['connection_method'])) {
        $method = $this->config['connection_method'];
    }
    $sql.= "{$method} '{$this->config['charset']}'";
    if ($method == 'SET NAMES' && !empty($this->config['collation'])) {
        $sql.= " COLLATE '{$this->config['collation']}'";
    }
    $this->pdo->exec($sql);
$this->pdo->exec("SET SESSION sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';");
}
```

**Comment by prioritypie** [comment]
Rather than closing this issue with a workaround, would it be better to adjust the code to avoid it anyway? I think the problem occurs in `/core/components/gallery/processors/mgr/item/getlist.class.php` in the `prepareQueryAfterCount` method.
Adding the rank column to the group_by prevents the error occurring:
```
~Line 65
	    $c->groupBy('id');
	    // Add the `rank` column to the group_by clause
	    $c->groupBy('rank');
	    return $c;
```

**Comment by Jako** [comment]
I think your suggested patch is wrong. There has no groupBy('rank') to be added to the GROUPBY clause to avoid the issue but the right 'rank' field has to be added to the SELECT clause.

**Comment by jacobkball** [comment]
This issue is still a problem, so I'm wondering if it will get fixed in an update to Gallery?

The only thing that fixed it for me was adding:

$this->pdo->exec("SET SESSION sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';");

to the connect.inc.php file per soydemadrid's answer, but it's hardly a permanent solution, is it?
