### ISSUE TITLE
Create directory problem, when MODX_BASE_PATH = /

### ISSUE THREAD

**Issue by jakub-gawryl** [modxcms/Gallery#76]
I noticed that, when my MODX_BASE_PATH is set to "/" it make problems with creating gallery album directories. Problem is caused by line 202 in galalbum.class.php: $targetDir = str_ireplace(MODX_BASE_PATH, '', $this->getPath()); which replaces all occurence of "/" in path name. So instead of create "gallery/album/2" it creates galleryalbum2 directory in base directory.

I think. there is simple solution just to add check whenever MODX_BASE_PATH is "/".
I'd like to create pull request, but im not fully sure about this solution, and now i need to handle this problem on every of my pages.

**Comment by Mark-H** [comment]
I do not think that a `MODX_BASE_PATH` of `/` is a valid configuration? You run MODX from the very root of your machine?
