### ISSUE TITLE
Cannot update Gallery to 1.7.1 - vulnerability clean version

### ISSUE THREAD

**Issue by mkilinskidev** [modxcms/Gallery#78]
Hi there. I have a big problem with update only this Extra on my site. In general, I have 3 websites based on Modx and in only one cant update. Here is the log:
[output-2018-07-23 1535.txt](https://github.com/modxcms/Gallery/files/2220694/output-2018-07-23.1535.txt)

I'd like to say that the database works normally... I can update others Extras, but not this. How can I update it manually? One of my sites was infected so I am upgrading all of my Modx sites, but this one doesn't want to be upgraded :)

**Comment by Mark-H** [comment]
For some reason, your database server wasn't available, which has very little to do with Gallery. 

If it happens consistently, and you think the installation is causing your server to crash, perhaps you need to upgrade your server so that it can handle a few extra queries being sent to it ;)
