### ISSUE TITLE
Gallery doesn't display images in manager view 

### ISSUE THREAD

**Issue by roilen** [modxcms/Gallery#79]
Hello! 

I have Gallery 1.7.1-pl and MODX Revolution 2.6.5-pl installed, Ubuntu 18.04 and MySQL 8.0 if it matters. 

So, I've successfully installed Gallery and can upload files, but they do not show up in album view. "No files match the specified filter."

I've double checked that files do exist in file manager and correctly shown in assets/gallery

ModX Error log shows the following line when I open the album page in manager: 

```
[2018-09-21 18:43:18] (ERROR @ /usr/share/nginx/artroilencom/core/xpdo/om/xpdoobject.class.php : 240) Error 42000 executing statement: 
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC LIMIT 20' at line 4
)
```

This line is for error debug information, nothing to do with the error itself.

**Comment by bcarrigg90** [comment]
I am having this issue as well. When uploading images through gallery, the single uploader shows the file path as C:\fakepath\image.jpg and nothing uploads. The multi uploader seems to work, as I can see the files in the modx file browser, but nothing shows in the gallery albums. It still always shows "No files match the specified filter."

**Comment by dstahlmann** [comment]
I have the same issue on my modx installation as well. I'am not able to figure out why. Have installed all neccessary dependencys on the server but still got the message.

**Comment by 000ParvejAlam** [comment]
https://github.com/modxcms/Gallery/issues/72#issuecomment-303684171

**Comment by 9thwave** [comment]
This issue was answered in this post: https://forums.modx.com/thread/104427/modx-gallery-doesn-t-show-images-in-manager-view
I can confirm that it works with Gallery 1.7.1 and Modx 2.8.0 by changing line 31 in core/components/gallery/processors/mgr/item/getlist.class.php.
from:
`public $defaultSortField = rank';`
to:
`public $defaultSortField = AlbumItems.rank';`
