### ISSUE TITLE
Revolution 3.0.0 Final: Gallery does not work

### ISSUE THREAD

**Issue by charismeki** [modxcms/Gallery#92]
Hi there,

we are facing an error after upgrading to MODx 3.0.0 in the Gallery Plugin. When trying to access it we get the error:
` An error occurred...
Error: Class GalleryManagerController not found
Errors:
    require_once()
    MODX\Revolution\modManagerResponse->getControllerClassName()
    MODX\Revolution\modManagerResponse->outputContent()
    MODX\Revolution\modManagerRequest->prepareResponse()
    MODX\Revolution\modManagerRequest->handleRequest()
`
We have tried to play around in the namespace but there is no chance to get the Gallery running. Is anybody out there updating the Gallery Add-On for MODx 3 or has an alternative suggestion what Add-on fits best? We have a loto of websites running using the Gallery Plugin so we are highly interested in an update.

Looking forward to any feedback in this.
Many thanks and best regards,
Markus

PS: The links if have posted my question already:
https://github.com/splittingred/Gallery/issues/302
https://community.modx.com/t/gallery-extra-compatible-with-modx-3-0-0/5163

**Comment by matdave** [comment]
fixed in latest release

**Comment by charismeki** [comment]
Thank you very much! I will PM you
